# default configurations for connecting
# and creating the search url
# note: all of these options can be overwritten by
#       adding to the query yaml (excluded options,
#       will default to the values in this yaml)

# defines the url to the search engine
url: http://search.twitter.com/search

# defines the parameters to add to the search url
params:
    rpp     : 100
    geo     :
    format  : json

# which objects to ignore
ignores: []

# how the get-twitter tool is configured, with
# max attemps and number of pages (of history)
# to pull down
configs:
    attempts: 10
    pages   : 150
    wait    : 5
    format  : '%m-%d-%Y %H:%M:%S'
